curl -o lib/angular.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.js
curl -o lib/angular-route.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-route.js
curl -o lib/angular-cookies.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-cookies.js
curl -o lib/angular-animate.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.js
curl -o lib/angular-aria.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.js
curl -o lib/angular-messages.js https//ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.js
curl -o lib/ngStorage.min.js http://cdn.jsdelivr.net/ngstorage/0.3.6/ngStorage.min.js
curl -o lib/angular-material.js http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.js
curl -o lib/angular-mocks.js http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-mocks.js